
devices:
  samplerate: 44100
  chunksize: 2048
  queuelimit: 1
  capture:
    type: File
    channels: 2
    filename: "/dev/stdin"
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:2,0"
    format: S32LE
filters:
    mastergain:
        type: Gain
        parameters:
            gain: -15
    ir_left:
      type: Conv
      parameters:
        type: File
        filename: ../coeffs/Sennheiser HD 800 S minimum phase 44100Hz_L.wav
        format: S16LE
    ir_right:
      type: Conv
      parameters:
        type: File
        filename: ../coeffs/Sennheiser HD 800 S minimum phase 44100Hz_R.wav
        format: S16LE
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
pipeline:
  - type: Mixer
    name: stereo
  - type: Filter
    channel: 0
    names:
      - mastergain
      - ir_left
  - type: Filter
    channel: 1
    names:
      - mastergain
      - ir_right

