devices:
  adjust_period: 10
  capture:
    channels: 2
    extra_samples: 0
    filename: /dev/stdin
    format: S16LE
    read_bytes: 0
    skip_bytes: 0
    type: File
  capture_samplerate: 0
  chunksize: 1024
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 2
    device: "plughw:0,0"
    format: S16LE
    type: Alsa
  queuelimit: 1
  resampler_type: BalancedAsync
  samplerate: 44100
  silence_threshold: 0
  silence_timeout: 0
  target_level: 0
filters:
  peqgain:
    type: Gain
    parameters:
      gain: -6.0
      inverted: false
  band_01:
    type: Biquad
    parameters:
      type: Peaking
      freq: 23
      q: 0.93
      gain: 5.6
  band_02:
    type: Biquad
    parameters:
      type: Peaking
      freq: 61
      q: 2.48
      gain: 1.9
  band_03:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1702
      q: 2.13
      gain: 3.2
  band_04:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3286
      q: 3.95
      gain: 2.6
  band_05:
    type: Biquad
    parameters:
      type: Peaking
      freq: 5648
      q: 3.94
      gain: -4.6
  band_06:
    type: Biquad
    parameters:
      type: Peaking
      freq: 210
      q: 1.32
      gain: -2.3
  band_07:
    type: Biquad
    parameters:
      type: Peaking
      freq: 449
      q: 0.72
      gain: -0.7
  band_08:
    type: Biquad
    parameters:
      type: Peaking
      freq: 4393
      q: 0.22
      gain: 0.2
  band_09:
    type: Biquad
    parameters:
      type: Peaking
      freq: 10533
      q: 1.17
      gain: 2.2
  band_10:
    type: Biquad
    parameters:
      type: Peaking
      freq: 19366
      q: 0.38
      gain: -11.6
mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      sources:
      - channel: 0
        gain: 0
        inverted: false
    - dest: 1
      sources:
      - channel: 1
        gain: 0
        inverted: false
pipeline:
- type: Mixer
  name: stereo
- type: Filter
  channel: 0
  names:
  - peqgain
  - band_01
  - band_02
  - band_03
  - band_04
  - band_05
  - band_06
  - band_07
  - band_08
  - band_09
  - band_10
- type: Filter
  channel: 1
  names:
  - peqgain
  - band_01
  - band_02
  - band_03
  - band_04
  - band_05
  - band_06
  - band_07
  - band_08
  - band_09
  - band_10
